/**
 * Domain types — kept in sync with the Python side by convention.
 *
 * The plan is to replace this file with `schema.gen.ts` (generated by
 * `pnpm gen:api` from FastAPI's OpenAPI document) once the API is running.
 * Until then, these hand-written types let the UI compile without
 * requiring the backend to be up at install time.
 */

export type ClassLevel = "class_11" | "class_12" | "dropper";

export type ExamTarget =
  | "jee_main"
  | "jee_advanced"
  | "neet"
  | "jee_main_advanced";

export type Language = "en" | "hi" | "hi-en";

export type Archetype =
  | "weak_concepts_hardworking"
  | "strong_concepts_poor_execution"
  | "class_11_foundation"
  | "class_12_balanced"
  | "dropper"
  | "unclassified";

export type OnboardingStatus = "in_progress" | "complete";

export interface QuestionPayload {
  question_id: string;
  text: string;
  category: string;
  /** "single_choice" | "multi_choice" | "short_text" | "number" */
  answer_type: string;
  options: string[];
}

export interface ProfileSummary {
  student_id: string;
  class_level: ClassLevel;
  exam_target: ExamTarget;
  language: Language;
  weak_subject: string | null;
  strong_subject: string | null;
  main_problem: string | null;
  learning_style: string | null;
  archetype: Archetype;
  profile_confidence: number;
  missing_critical_fields: string[];
}

export interface OnboardingStateResponse {
  status: OnboardingStatus;
  profile: ProfileSummary;
  next_question: QuestionPayload | null;
}

export interface StartOnboardingRequest {
  student_id: string;
  class_level: ClassLevel;
  exam_target: ExamTarget;
  language?: Language;
  display_name?: string | null;
  email?: string | null;
}

export interface SubmitAnswerRequest {
  student_id: string;
  question_id: string;
  raw_answer: string;
}

/**
 * Shape returned by the FastAPI error handlers in `apps/api/.../errors.py`.
 */
export interface ApiErrorBody {
  code: string;
  message: string;
}

export type ChatRole = "user" | "assistant";

export interface ChatMessage {
  role: ChatRole;
  content: string;
}

export interface ChatStreamRequest {
  student_id: string;
  question: string;
  language?: Language;
  history: ChatMessage[];
}

/**
 * Discriminated union of SSE events emitted by `POST /api/v1/chat/stream`.
 * Matches the `event:` line in each frame from `routers/chat.py`.
 */
export type ChatStreamEvent =
  | { kind: "delta"; text: string }
  | {
      kind: "done";
      model: string | null;
      usage: { input_tokens: number; output_tokens: number } | null;
      cost_usd: number | null;
    }
  | { kind: "error"; message: string };
